2024-08-03 12:30:12,217  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2024-08-03 12:30:17,652 127.0.0.1 - - [03/Aug/2024 12:30:17] "GET / HTTP/1.1" 200 -
2024-08-03 12:30:17,930 127.0.0.1 - - [03/Aug/2024 12:30:17] "GET /UndergradMap/static/styles/mainpage.css HTTP/1.1" 304 -
2024-08-03 12:30:17,988 127.0.0.1 - - [03/Aug/2024 12:30:17] "GET /UndergradMap/static/styles/coverpage.css HTTP/1.1" 304 -
2024-08-03 12:30:17,989 127.0.0.1 - - [03/Aug/2024 12:30:17] "GET /UndergradMap/static/styles/wholesem.css HTTP/1.1" 304 -
2024-08-03 12:30:17,989 127.0.0.1 - - [03/Aug/2024 12:30:17] "GET /UndergradMap/static/styles/tooltip.css HTTP/1.1" 304 -
2024-08-03 12:30:17,989 127.0.0.1 - - [03/Aug/2024 12:30:17] "GET /UndergradMap/static/styles/sembysem.css HTTP/1.1" 304 -
2024-08-03 12:30:17,990 127.0.0.1 - - [03/Aug/2024 12:30:17] "GET /UndergradMap/static/js/drag_drop_utils.js HTTP/1.1" 304 -
2024-08-03 12:30:18,238 127.0.0.1 - - [03/Aug/2024 12:30:18] "GET /UndergradMap/static/js/initial_page_utils.js HTTP/1.1" 304 -
2024-08-03 12:30:18,300 127.0.0.1 - - [03/Aug/2024 12:30:18] "GET /UndergradMap/static/js/schedule_display_utils.js HTTP/1.1" 304 -
2024-08-03 12:30:18,300 127.0.0.1 - - [03/Aug/2024 12:30:18] "GET /UndergradMap/static/js/save_load.js HTTP/1.1" 304 -
2024-08-03 12:30:18,683 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:18,690 127.0.0.1 - - [03/Aug/2024 12:30:18] "GET /favicon.ico HTTP/1.1" 500 -
2024-08-03 12:30:18,710 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:22,868 Exception on /schedule [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2042, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 15, in error_405
    return render_template('errors/405.html'), 405
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\405.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:22,870 127.0.0.1 - - [03/Aug/2024 12:30:22] "GET /schedule HTTP/1.1" 500 -
2024-08-03 12:30:22,872 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2042, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 15, in error_405
    return render_template('errors/405.html'), 405
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\405.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:23,206 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:23,208 127.0.0.1 - - [03/Aug/2024 12:30:23] "GET /favicon.ico HTTP/1.1" 500 -
2024-08-03 12:30:23,209 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:31,398 Exception on /sd [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:31,400 127.0.0.1 - - [03/Aug/2024 12:30:31] "GET /sd HTTP/1.1" 500 -
2024-08-03 12:30:31,402 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:31,739 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:31,741 127.0.0.1 - - [03/Aug/2024 12:30:31] "GET /favicon.ico HTTP/1.1" 500 -
2024-08-03 12:30:31,743 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:34,260 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET / HTTP/1.1" 200 -
2024-08-03 12:30:34,588 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET /UndergradMap/static/styles/tooltip.css HTTP/1.1" 304 -
2024-08-03 12:30:34,588 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET /UndergradMap/static/styles/coverpage.css HTTP/1.1" 304 -
2024-08-03 12:30:34,589 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET /UndergradMap/static/styles/mainpage.css HTTP/1.1" 304 -
2024-08-03 12:30:34,589 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET /UndergradMap/static/styles/sembysem.css HTTP/1.1" 304 -
2024-08-03 12:30:34,589 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET /UndergradMap/static/styles/wholesem.css HTTP/1.1" 304 -
2024-08-03 12:30:34,590 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET /UndergradMap/static/js/initial_page_utils.js HTTP/1.1" 304 -
2024-08-03 12:30:34,900 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET /UndergradMap/static/js/drag_drop_utils.js HTTP/1.1" 304 -
2024-08-03 12:30:34,901 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET /UndergradMap/static/js/save_load.js HTTP/1.1" 304 -
2024-08-03 12:30:34,901 127.0.0.1 - - [03/Aug/2024 12:30:34] "GET /UndergradMap/static/js/schedule_display_utils.js HTTP/1.1" 304 -
2024-08-03 12:30:35,232 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:35,234 127.0.0.1 - - [03/Aug/2024 12:30:35] "GET /favicon.ico HTTP/1.1" 500 -
2024-08-03 12:30:35,236 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:36,544 Exception on /UndergradMap/schedule [POST]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:36,546 127.0.0.1 - - [03/Aug/2024 12:30:36] "POST /UndergradMap/schedule HTTP/1.1" 500 -
2024-08-03 12:30:36,548 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:36,880 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:36,882 127.0.0.1 - - [03/Aug/2024 12:30:36] "GET /favicon.ico HTTP/1.1" 500 -
2024-08-03 12:30:36,884 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:40,600 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:40,602 127.0.0.1 - - [03/Aug/2024 12:30:40] "GET /favicon.ico HTTP/1.1" 500 -
2024-08-03 12:30:40,604 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:40,914 127.0.0.1 - - [03/Aug/2024 12:30:40] "GET /UndergradMap/static/styles/mainpage.css HTTP/1.1" 304 -
2024-08-03 12:30:40,915 127.0.0.1 - - [03/Aug/2024 12:30:40] "GET /UndergradMap/static/styles/coverpage.css HTTP/1.1" 304 -
2024-08-03 12:30:40,915 127.0.0.1 - - [03/Aug/2024 12:30:40] "GET /UndergradMap/static/styles/sembysem.css HTTP/1.1" 304 -
2024-08-03 12:30:40,916 127.0.0.1 - - [03/Aug/2024 12:30:40] "GET /UndergradMap/static/styles/wholesem.css HTTP/1.1" 304 -
2024-08-03 12:30:40,916 127.0.0.1 - - [03/Aug/2024 12:30:40] "GET /UndergradMap/static/styles/tooltip.css HTTP/1.1" 304 -
2024-08-03 12:30:42,110 Exception on /UndergradMap/schedule [POST]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:42,112 127.0.0.1 - - [03/Aug/2024 12:30:42] "POST /UndergradMap/schedule HTTP/1.1" 500 -
2024-08-03 12:30:42,114 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:42,455 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:42,457 127.0.0.1 - - [03/Aug/2024 12:30:42] "GET /favicon.ico HTTP/1.1" 500 -
2024-08-03 12:30:42,459 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:43,647 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
2024-08-03 12:30:43,650 127.0.0.1 - - [03/Aug/2024 12:30:43] "GET /favicon.ico HTTP/1.1" 500 -
2024-08-03 12:30:43,653 Error on request:
Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 7, in error_404
    return render_template('errors/404.html'), 404
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\404.html", line 15, in top-level template code
    <p>Double-check the URL or <a href="{{ url_for('UndergradMap') }}">head back</a> to the homepage</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\app.py", line 1440, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\errors\handlers.py", line 19, in error_500
    return render_template('errors/500.html'), 500
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\app\templates\errors\500.html", line 15, in top-level template code
    <p><a href="{{ url_for('UndergradMap') }}">Head back</a> to the homepage to restart.</p>
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jordan\projects\UMSL_Course_Scheduler\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'UndergradMap'. Did you mean 'index' instead?
